#**Assignment 07: Classification Algorithms Model Building**

In [86]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

##**Task 1 – Data Exploration & Preprocessing**

**Assignment 07: Classification Algorithms Model Building**

In [87]:
#loading the dataset
df = pd.read_csv("https://raw.githubusercontent.com/Chenneumakanth/Classification-Algorithms-Model-Building/refs/heads/main/crowdfunding.csv")

In [88]:
#Inspect the dataset head
df.head()

,Unnamed: 0,CampaignID,GoalAmount,RaisedAmount,DurationDays,NumBackers,Category,LaunchMonth,Country,Currency,OwnerExperience,VideoIncluded,SocialMediaPresence,NumUpdates,IsSuccessful
0,0,CID_00000,76159,73518.028955,15,1903,Film,September,Australia,GBP,11,Yes,41758,3,0
1,1,CID_00001,69394,60068.683288,49,469,Art,October,Australia,GBP,7,Yes,79112,48,0
2,2,CID_00002,18652,22958.153470,58,148,Film,February,USA,EUR,17,No,3942,9,1
3,3,CID_00003,19487,24229.048390,39,780,Film,October,Germany,AUD,10,No,22047,35,1
4,4,CID_00004,26734,17984.630311,68,1622,Games,September,Australia,AUD,12,Yes,72568,17,0

In [89]:
#Inspect the dataset tail
df.tail()

,Unnamed: 0,CampaignID,GoalAmount,RaisedAmount,DurationDays,NumBackers,Category,LaunchMonth,Country,Currency,OwnerExperience,VideoIncluded,SocialMediaPresence,NumUpdates,IsSuccessful
99995,99995,CID_99995,80417,112068.932642,26,870,Music,October,UK,AUD,6,No,84173,8,1
99996,99996,CID_99996,85052,100430.502040,78,1146,Film,October,USA,USD,8,No,13913,42,1
99997,99997,CID_99997,68407,102020.936312,87,636,Art,March,UK,EUR,2,Yes,45273,13,1
99998,99998,CID_99998,59749,67026.111706,51,1276,Music,August,Australia,CAD,10,Yes,67574,29,1
99999,99999,CID_99999,39913,54863.288105,73,695,Film,April,Germany,CAD,11,No,84806,41,1

In [90]:
#Inspect the dataset columns
df.columns

Index(['Unnamed: 0', 'CampaignID', 'GoalAmount', 'RaisedAmount',
       'DurationDays', 'NumBackers', 'Category', 'LaunchMonth', 'Country',
       'Currency', 'OwnerExperience', 'VideoIncluded', 'SocialMediaPresence',
       'NumUpdates', 'IsSuccessful'],
      dtype='object')

In [91]:
#Inspect the dataset dtypes
df.dtypes

Unnamed: 0               int64
CampaignID              object
GoalAmount               int64
RaisedAmount           float64
DurationDays             int64
NumBackers               int64
Category                object
LaunchMonth             object
Country                 object
Currency                object
OwnerExperience          int64
VideoIncluded           object
SocialMediaPresence      int64
NumUpdates               int64
IsSuccessful             int64
dtype: object

In [92]:
#Inspect the dataset null values
df.isnull().sum()

Unnamed: 0             0
CampaignID             0
GoalAmount             0
RaisedAmount           0
DurationDays           0
NumBackers             0
Category               0
LaunchMonth            0
Country                0
Currency               0
OwnerExperience        0
VideoIncluded          0
SocialMediaPresence    0
NumUpdates             0
IsSuccessful           0
dtype: int64

In [93]:
#Inspect the dataset shape
df.shape

(100000, 15)

In [94]:
#Inspect the dataset info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 15 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Unnamed: 0           100000 non-null  int64
 1   CampaignID           100000 non-null  object
 2   GoalAmount           100000 non-null  int64
 3   RaisedAmount         100000 non-null  float64
 4   DurationDays         100000 non-null  int64
 5   NumBackers           100000 non-null  int64
 6   Category             100000 non-null  object
 7   LaunchMonth          100000 non-null  object
 8   Country              100000 non-null  object
 9   Currency             100000 non-null  object
 10  OwnerExperience      100000 non-null  int64
 11  VideoIncluded        100000 non-null  object
 12  SocialMediaPresence  100000 non-null  int64
 13  NumUpdates           100000 non-null  int64
 14  IsSuccessful         100000 non-null  int64
dtypes: float64(1), int64(8), object(6)
memory usage: 11.4+ MB

In [95]:
#Inspect the dataset describe
df.describe()

,Unnamed: 0,GoalAmount,RaisedAmount,DurationDays,NumBackers,OwnerExperience,SocialMediaPresence,NumUpdates,IsSuccessful
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,49999.500000,50538.001310,50598.121803,52.047370,1003.347340,9.489130,50077.301010,24.483230,0.500940
std,28867.657797,28613.822592,33255.277493,21.653238,574.485153,5.763538,28767.521522,14.413833,0.500002
min,0.000000,1000.000000,528.632349,15.000000,10.000000,0.000000,100.000000,0.000000,0.000000
25%,24999.750000,25724.750000,23396.500017,33.000000,505.000000,4.000000,25276.750000,12.000000,0.000000
50%,49999.500000,50706.000000,45980.674476,52.000000,1003.000000,9.000000,50024.500000,25.000000,1.000000
75%,74999.250000,75316.000000,72790.183158,71.000000,1502.000000,14.000000,74934.250000,37.000000,1.000000
max,99999.000000,99999.000000,149238.361559,89.000000,1999.000000,19.000000,99999.000000,49.000000,1.000000

**Handle missing values and duplicates**

In [96]:
#missing values
df.isnull().sum()

Unnamed: 0             0
CampaignID             0
GoalAmount             0
RaisedAmount           0
DurationDays           0
NumBackers             0
Category               0
LaunchMonth            0
Country                0
Currency               0
OwnerExperience        0
VideoIncluded          0
SocialMediaPresence    0
NumUpdates             0
IsSuccessful           0
dtype: int64

In [97]:
#duplicates
df.duplicated().sum()

np.int64(0)

In [98]:
df.drop(columns=["Unnamed: 0"],inplace=True)

In [99]:
df.head()

,CampaignID,GoalAmount,RaisedAmount,DurationDays,NumBackers,Category,LaunchMonth,Country,Currency,OwnerExperience,VideoIncluded,SocialMediaPresence,NumUpdates,IsSuccessful
0,CID_00000,76159,73518.028955,15,1903,Film,September,Australia,GBP,11,Yes,41758,3,0
1,CID_00001,69394,60068.683288,49,469,Art,October,Australia,GBP,7,Yes,79112,48,0
2,CID_00002,18652,22958.153470,58,148,Film,February,USA,EUR,17,No,3942,9,1
3,CID_00003,19487,24229.048390,39,780,Film,October,Germany,AUD,10,No,22047,35,1
4,CID_00004,26734,17984.630311,68,1622,Games,September,Australia,AUD,12,Yes,72568,17,0

**Encode categorical variables**

In [100]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["Category"] = le.fit_transform(df["Category"])
df["LaunchMonth"] = le.fit_transform(df["LaunchMonth"])
df["Country"] = le.fit_transform(df["Country"])
df["Currency"] = le.fit_transform(df["Currency"])
df["VideoIncluded"] = le.fit_transform(df["VideoIncluded"])

**Perform feature selection**

In [101]:
corr_matrix=df.corr(numeric_only=True)

In [102]:
df['IsSuccessful'].unique()

array([0, 1])

In [103]:
target_correlations = corr_matrix['IsSuccessful'].sort_values(ascending=False)
print(target_correlations)

IsSuccessful           1.000000
RaisedAmount           0.384000
GoalAmount             0.004240
Currency               0.003088
VideoIncluded          0.002807
DurationDays           0.002787
Category               0.001984
NumUpdates             0.000530
SocialMediaPresence    0.000442
LaunchMonth           -0.001153
Country               -0.001269
NumBackers            -0.002590
OwnerExperience       -0.007015
Name: IsSuccessful, dtype: float64

In [104]:
target_correlations["IsSuccessful"]

np.float64(1.0)

In [105]:
#Feature target
y = df[['IsSuccessful']]
y

       IsSuccessful
0                 0
1                 0
2                 1
3                 1
4                 0
...             ...
99995             1
99996             1
99997             1
99998             1
99999             1

[100000 rows x 1 columns]

In [106]:
#Feature selection
from sklearn.feature_selection import SelectKBest,f_classif
df_numeric = df.select_dtypes(include=['number'])
selector = SelectKBest(score_func=f_classif, k=8)


x= selector.fit_transform(df_numeric,y)
feature_scores = selector.scores_

selected_indices = selector.get_support(indices=True)
chosen_feature_names = df_numeric.columns[selected_indices]

# 2. Convert your numpy array 'x' back into a beautiful DataFrame
x = pd.DataFrame(x, columns=chosen_feature_names)

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.13/dist-packages/sklearn/feature_selection/_univariate_selection.py:112: RuntimeWarning: divide by zero encountered in divide
  f = msb / msw

In [107]:
##x = x.drop('RaisedAmount', axis=1, errors='ignore')

In [108]:
x = x.drop('IsSuccessful', axis=1, errors='ignore')

In [109]:
x

,GoalAmount,RaisedAmount,DurationDays,NumBackers,Currency,OwnerExperience,VideoIncluded
0,76159.0,73518.028955,15.0,1903.0,3.0,11.0,1.0
1,69394.0,60068.683288,49.0,469.0,3.0,7.0,1.0
2,18652.0,22958.153470,58.0,148.0,2.0,17.0,0.0
3,19487.0,24229.048390,39.0,780.0,0.0,10.0,0.0
4,26734.0,17984.630311,68.0,1622.0,0.0,12.0,1.0
...,...,...,...,...,...,...,...
99995,80417.0,112068.932642,26.0,870.0,0.0,6.0,0.0
99996,85052.0,100430.502040,78.0,1146.0,4.0,8.0,0.0
99997,68407.0,102020.936312,87.0,636.0,2.0,2.0,1.0
99998,59749.0,67026.111706,51.0,1276.0,1.0,10.0,1.0
99999,39913.0,54863.288105,73.0,695.0,1.0,11.0,0.0

In [110]:
import warnings

In [111]:
from sklearn.model_selection import train_test_split,GridSearchCV


x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=16)

In [112]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [113]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

models = {
    "Random Forest": RandomForestClassifier(random_state=42),
    "KNN (K-Nearest Neighbors)": KNeighborsClassifier(n_neighbors=5),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Naive Bayes": GaussianNB(),
    "Support Vector Machine (SVM)": SVC(kernel='rbf', random_state=42)
}
results = {}
for name, model in models.items():
   model.fit(x_train, y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.13/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [114]:

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
evaluation_results = []



for name, model in models.items():
    y_train_pred = model.predict(x_train)
    y_test_pred = model.predict(x_test)

    # 2. Calculate requested Performance Metrics
    metrics = {
        "Train Accuracy": accuracy_score(y_train, y_train_pred),
        "Test Accuracy": accuracy_score(y_test, y_test_pred),
        "Train Precision": precision_score(y_train, y_train_pred),
        "Test Precision": precision_score(y_test, y_test_pred),
        "Train Recall": recall_score(y_train, y_train_pred),
        "Test Recall": recall_score(y_test, y_test_pred),
        "Train F1-Score": f1_score(y_train, y_train_pred),
        "Test F1-Score": f1_score(y_test, y_test_pred),
    }
    evaluation_results.append(metrics)

    # 3. Generate Confusion Matrices
    cm_train = confusion_matrix(y_train, y_train_pred)
    cm_test = confusion_matrix(y_test, y_test_pred)

    # Print individual reports to console
    print(f"  {name} Metrics:")
    print(f"   [Train vs Test Accuracy]: {metrics['Train Accuracy']:.4f} vs {metrics['Test Accuracy']:.4f}")
    print(f"   [Train vs Test F1-Score]: {metrics['Train F1-Score']:.4f} vs {metrics['Test F1-Score']:.4f}")
    print(f"   Test Confusion Matrix:\n  {cm_test}\n")

  Random Forest Metrics:
   [Train vs Test Accuracy]: 1.0000 vs 0.9827
   [Train vs Test F1-Score]: 1.0000 vs 0.9824
   Test Confusion Matrix:
  [[9974  124]
 [ 222 9680]]

  KNN (K-Nearest Neighbors) Metrics:
   [Train vs Test Accuracy]: 0.9151 vs 0.8422
   [Train vs Test F1-Score]: 0.9152 vs 0.8401
   Test Confusion Matrix:
  [[8556 1542]
 [1614 8288]]

  Decision Tree Metrics:
   [Train vs Test Accuracy]: 1.0000 vs 0.9931
   [Train vs Test F1-Score]: 1.0000 vs 0.9931
   Test Confusion Matrix:
  [[10021    77]
 [   60  9842]]

  Naive Bayes Metrics:
   [Train vs Test Accuracy]: 0.6642 vs 0.6670
   [Train vs Test F1-Score]: 0.6089 vs 0.6073
   Test Confusion Matrix:
  [[8191 1907]
 [4753 5149]]

  Support Vector Machine (SVM) Metrics:
   [Train vs Test Accuracy]: 0.9863 vs 0.9840
   [Train vs Test F1-Score]: 0.9863 vs 0.9838
   Test Confusion Matrix:
  [[9993  105]
 [ 214 9688]]

Decision Tree achieved the highest test accuracy (99.31%), closely followed by the SVM (98.40%). While the Random Forest and Decision Tree still hit a perfect 1.0000 on the training data, they only dropped by ~1% on the test set. Naive Bayes (66.70%) and KNN (84.22%) performed poorly because they cannot handle columns that correlate with each other

###**Task 4 – Cross-Validation & Hyperparameter Tuning**

In [115]:
import warnings

**Apply Cross-Validation to evaluate model stability**

In [116]:
from sklearn.model_selection import StratifiedKFold,GridSearchCV,RandomizedSearchCV
cv=StratifiedKFold(n_splits=5,shuffle=True,random_state=42)

**Perform Hyperparameter Tuning using GridSearchCV or RandomizedSearchCV**

In [117]:
#Random Forest (RandomizedSearchCV)
rf_param_dist = {
    'n_estimators': [50, 100, 150],
    'max_depth': [3, 5, 10, None],
    'min_samples_split': [2, 5]
}

In [118]:
from sklearn.model_selection import train_test_split,StratifiedKFold,GridSearchCV,RandomizedSearchCV
rf_grid=RandomizedSearchCV(RandomForestClassifier(random_state=42),param_distributions=rf_param_dist,cv=cv,scoring='accuracy',verbose=1,n_jobs=-1)
rf_grid.fit(x_train,y_train)
rf_best_parameter = rf_grid.best_params_
print(f'Best parameters:{rf_best_parameter}')
rf_best_score = rf_grid.best_score_
print(f'Best score:{rf_grid.best_score_}')

Fitting 5 folds for each of 10 candidates, totalling 50 fits

/usr/local/lib/python3.13/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Best parameters:{'n_estimators': 100, 'min_samples_split': 5, 'max_depth': None}
Best score:0.983775

In [119]:
# support Vector Classifier (GridSearchCV)

svc_param_grid = {'C': [0.1, 1, 10], 'gamma': ['scale', 'auto'], 'kernel': ['rbf', 'linear']}

In [120]:
"""
svc_random = RandomizedSearchCV(
    estimator=SVC(),
    param_distributions=svc_param_grid,
    n_iter=6,           # Only tests 6 random combinations instead of all 12
    cv=cv,
    scoring='accuracy',
    verbose=1,
     n_jobs=-1,
    random_state=42
)
svc_random.fit(x_train, y_train)
svc_best_parameter = svc_random.best_params_
print(f'Best parameters:{svc_best_parameter}')
svc_best_score = svc_random.best_score_
print(f'Best score:{svc_best_score}')
"""

"\nsvc_random = RandomizedSearchCV(\n    estimator=SVC(),\n    param_distributions=svc_param_grid,\n    n_iter=6,           # Only tests 6 random combinations instead of all 12\n    cv=cv,\n    scoring='accuracy',\n    verbose=1,\n     n_jobs=-1,\n    random_state=42\n)\nsvc_random.fit(x_train, y_train)\nsvc_best_parameter = svc_random.best_params_\nprint(f'Best parameters:{svc_best_parameter}')\nsvc_best_score = svc_random.best_score_\nprint(f'Best score:{svc_best_score}')\n"

In [121]:
#KNN (Grid search cv)
knn_param_grid = {
    'n_neighbors': [3, 5, 7],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan']
}

In [122]:
import numpy as np
knn_grid = GridSearchCV(
    estimator=KNeighborsClassifier(),
    param_grid=knn_param_grid,
    cv=cv,
    scoring='accuracy',
    verbose=1,
    n_jobs=-1
)
knn_grid.fit(x_train, y_train)
knn_best_parameter = knn_grid.best_params_
print(f'Best parameters:{knn_best_parameter}')
knn_best_score = knn_grid.best_score_
print(f'Best score:{knn_best_score}')

Fitting 5 folds for each of 12 candidates, totalling 60 fits
Best parameters:{'metric': 'manhattan', 'n_neighbors': 7, 'weights': 'distance'}
Best score:0.852275

/usr/local/lib/python3.13/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

In [123]:
#Naive buyers (Grid search cv)
nb_param_grid = {
    'var_smoothing': np.logspace(0, -9, num=9)
}

In [124]:
nb_grid = GridSearchCV(
    estimator=GaussianNB(),
    param_grid=nb_param_grid,
    cv=cv,
    scoring='accuracy',
    verbose=1,
    n_jobs=-1
)
nb_grid.fit(x_train, y_train)
nb_best_parameter = nb_grid.best_params_
print(f'Best parameters:{nb_best_parameter}')
nb_best_score = nb_grid.best_score_
print(f'Best score:{nb_best_score}')

Fitting 5 folds for each of 9 candidates, totalling 45 fits
Best parameters:{'var_smoothing': np.float64(1.0)}
Best score:0.6663250000000001

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [125]:
dt_param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [None, 3, 5, 10, 15],
    'min_samples_split': [2, 5, 10]
}

In [126]:
dt_grid = GridSearchCV(
    estimator=DecisionTreeClassifier(random_state=42),
    param_grid=dt_param_grid,
    cv=cv,
    scoring='accuracy',
    verbose=1,
    n_jobs=-1
)
dt_grid.fit(x_train, y_train)
dt_best_parameter = dt_grid.best_params_
print(f'Best parameters:{dt_best_parameter}')
dt_best_score = dt_grid.best_score_
print(f'Best score:{dt_best_score}')

Fitting 5 folds for each of 30 candidates, totalling 150 fits
Best parameters:{'criterion': 'entropy', 'max_depth': None, 'min_samples_split': 5}
Best score:0.9925875

**Identify the best parameters for each model**

In [127]:
models_hyper = {
    "Random Forest": rf_best_parameter,
    "KNN": knn_best_parameter,
    "Decision Tree": dt_best_parameter,
    "Naive Bayes": nb_best_parameter
    ##"SVM":
}
best_models = pd.DataFrame(list(models_hyper.items()), columns=['Model', 'Parameters'])
best_models

           Model                                         Parameters
0  Random Forest  {'n_estimators': 100, 'min_samples_split': 5, ...
1            KNN  {'metric': 'manhattan', 'n_neighbors': 7, 'wei...
2  Decision Tree  {'criterion': 'entropy', 'max_depth': None, 'm...
3    Naive Bayes                             {'var_smoothing': 1.0}

##**Task 5 – Model Comparison & Selection**

####**Compare all classification models using evaluation metrics**

In [128]:
best_models = {
    "Random Forest": rf_grid.best_estimator_,
    "KNN": knn_grid.best_estimator_,
    "Decision Tree": dt_grid.best_estimator_,
    "Naive Bayes": nb_grid.best_estimator_,
    ##"SVM": svc_grid.best_estimator_
}
final_comparison = []
for name, model in best_models.items():
    y_pred = model.predict(x_test)
    final_comparison.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1-Score": f1_score(y_test, y_pred)
    })

df_comparison = pd.DataFrame(final_comparison).sort_values(by="F1-Score", ascending=False)
df_comparison

           Model  Accuracy  Precision    Recall  F1-Score
2  Decision Tree   0.99455   0.994946  0.994042  0.994494
0  Random Forest   0.98325   0.987863  0.978186  0.983001
1            KNN   0.85585   0.858149  0.849222  0.853662
3    Naive Bayes   0.67050   0.755162  0.494951  0.597975

Based on a rigorous evaluation of the hyperparameter-tuned classification algorithms, the Decision Tree Classifier is selected as the optimal production model for predicting crowdfunding campaign success, achieving a near-flawless test accuracy of 99.46% and an F1-Score of 0.9945. While tree-based ensembles like Random Forest also demonstrated high robustness (98.33% accuracy), the slight performance edge of the single Decision Tree proves that the underlying dataset structure relies on clear, axis-aligned, logical feature thresholds rather than complex multi-feature interactions. Furthermore, the model exhibits exceptional stability, displaying tightly balanced Precision (99.49%) and Recall (99.40%) metrics

####**Identify the best-performing model**

The Decision Tree Classifier is selected as the definitive champion model for this dataset.It achieved peak validation stability with a near-flawless 99.46% accuracy and a perfectly symmetric balance between Precision (99.49%) and Recall (99.40%)

**Discuss strengths, weaknesses, and possible improvements**

• **Decision Tree**
	• Strength: Achieves peak accuracy (99.46%) by perfectly capturing crisp, razor-sharp logical boundaries in the data.
	• Weakness: Highly sensitive to data changes; risk of breaking if future data distributions drift.

• **Random Forest**
	• Strength: Excellent generalization and highly resilient against noise or dataset variance.
	• Weakness: Ensemble averaging slightly blurs the exact mathematical thresholds, dropping accuracy to 98.33%.

• **K-Nearest Neighbors (KNN)**
	• Strength: Simple, intuitive distance-based model that requires zero formal training time.
	• Weakness: Struggled heavily with multidimensional noise, leading to over 1,500 misclassifications (85.59% accuracy).

  
• **Naive Bayes**
	• Strength: Computationally lightweight, lightning-fast, and highly scalable.
	• Weakness: Total mathematical failure (67.05% accuracy); its assumption of independent features completely breaks down on correlating crowdfunding columns.